apply plugin: 'com.android.application'

android {
    compileSdk 25
    buildToolsVersion "25.0.2"
    namespace 'projekt.interfacer'

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    defaultConfig {
        applicationId "projekt.interfacer"
        minSdk 25
        targetSdk 25
        versionCode 62
        versionName "sixty two"
    }

    compileOptions {
        incremental true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "themeinterfacer.apk"
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dependencies {
        testImplementation 'junit:junit:4.12'
        implementation 'androidx.core:core-ktx:1.10.1'
        implementation 'androidx.appcompat:appcompat:1.6.1'
        implementation 'com.google.android.material:material:1.9.0'
        implementation 'de.robv.android.xposed:api:82'
        implementation 'de.robv.android.xposed:api:82:sources'
    }
}

tasks.register('copyApk', Copy) {
    from layouts.projectDirectory.dir("app/build/outputs/apk/debug")
    into layouts.projectDirectory.dir("release_apk/debug")
    include "themeinterfacer.apk"
    rename "themeinterfacer.apk", "themeinterfacer_${new Date().format('yyyyMMddHHmm')}.apk"
}

tasks.register('buildAndCopyApk') {
    dependsOn 'assembleDebug', 'copyApk'
}

tasks.register('createApkDirectory') {
    def dirDebug = file("release_apk/debug")
    if (!dirDebug.exists()) {
        dirDebug.mkdirs()
    }
    def dirRelease = file("release_apk/release")
    if (!dirRelease.exists()) {
        dirRelease.mkdirs()
    }
}
