apply plugin: 'com.android.application'

android {
    compileSdk 25
    buildToolsVersion "25.0.2"

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFile = new File(
                    output.outputFile.parent, "themeinterfacer_" + versionCode + ".apk")
        }
    }

    defaultConfig {
        applicationId "projekt.interfacer"
        minSdk 25
        targetSdk 25
        versionCode 62
        versionName "sixty two"
    }

    defaultConfig {
        jackOptions {
            enabled true
        }
    }

    compileOptions {
        incremental true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    dexOptions {
        javaMaxHeapSize '2048m'
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dependencies {
        testCompile 'junit:junit:4.12'
        implementation 'androidx.core:core-ktx:1.10.1'
        implementation 'androidx.appcompat:appcompat:1.6.1'
        implementation 'com.google.android.material:material:1.9.0'
        implementation 'de.robv.android.xposed:api:82'
        implementation 'de.robv.android.xposed:api:82:sources'
    }
}
