apply plugin: 'com.android.application'

android {
    compileSdk 34
    buildToolsVersion "34.0.0"
    namespace 'projekt.interfacer'

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    defaultConfig {
        applicationId "projekt.interfacer"
        minSdk 25
        targetSdk 34
        versionCode 62
        versionName "sixty two"
    }

    compileOptions {
        incremental true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "themeinterfacer.apk"
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dependencies {
        testImplementation 'junit:junit:4.12'
        implementation 'de.robv.android.xposed:api:82'
        implementation 'androidx.core:core-ktx:1.12.0'
        implementation 'androidx.appcompat:appcompat:1.6.1'
        implementation 'com.google.android.material:material:1.11.0'
        implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    }
}
