name: Build with Gradle

on:
  push:
    branches: [ n-rootless ]
  pull_request:
    branches: [ n-rootless ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: app/build/outputs/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/themeinterfacer.apk
